# Cấu hình chung
server:
  url: http://localhost:8080
  port: 8080  # Cổng của ứng dụng
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# Cấu hình kết nối cơ sở dữ liệu
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shopapp_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # Cấu hình kích thước pool kết nối
    jackson:
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
      time-zone: UTC

  web:
    resources:
      static-locations: file:/uploads/


  mvc:
    charset: UTF-8

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en


# Cấu hình JPA (Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: update  # Tự động tạo bảng nếu chưa có
    show-sql: true  # Hiển thị câu lệnh SQL trong console

# Cấu hình bảo mật
  security:
    enable: false
    user:
      name: admin
      password: password
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: contactwork004@gmail.com
    password: fctk himv rens tdgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


api:
  prefix: /api/v1

jwt:
  secretKey: 3fd00454580de44ea216d8b7b234267a2a6a6aec7e56d2b38e641a45597af0f2
  expiration: 2592000
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60

#  spring.jpa.hibernate.ddl-auto=none
