# Cấu hình chung
server:
  url: http://localhost:8080
  port: 8080  # Cổng của ứng dụng
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Cấu hình kết nối cơ sở dữ liệu
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shopapp_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # Cấu hình kích thước pool kết nối
    jackson:
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
      time-zone: UTC

  web:
    resources:
      static-locations: file:/uploads/

  mvc:
    charset: UTF-8

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en


# Cấu hình JPA (Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: update  # Tự động tạo bảng nếu chưa có
    show-sql: true  # Hiển thị câu lệnh SQL trong console

  jackson:
    mapper:
      accept-case-insensitive-enums: true  # Chấp nhận enum không phân biệt chữ hoa chữ thường

  # Cấu hình bảo mật
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        registration:
          google: # Đăng ký Google OAuth2 client
            client-id: 648757440833-sfda15k5qpfobvgrp33t5866b6gv1ji6.apps.googleusercontent.com   # ID của ứng dụng từ Google Cloud Console
            client-secret: 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  # Secret key từ Google Cloud Console
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:8080/api/v1/users/login/social/callback}"  # Đường dẫn callback sau khi đăng nhập thành công
            scope: # Các quyền (scopes) yêu cầu từ người dùng
              - email  # Truy cập email của người dùng
              - profile  # Truy cập thông tin hồ sơ (tên, ảnh đại diện,...)

    user:
      name: admin
      password: password

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: contactwork004@gmail.com
    password: fctk himv rens tdgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: /api/v1

jwt:
  secretKey: 3fd00454580de44ea216d8b7b234267a2a6a6aec7e56d2b38e641a45597af0f2
  expiration: 2592000
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60

# VNPay Sandbox Configuration
vnpay:
  vnp_TmnCode: "ATD2CAUF"
  vnp_HashSecret: "0ERA7PHSYV3CRFJB1W4OI04PZZDYZA2W"
  vnp_Url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  vnp_ReturnUrl: "http://localhost:8080/api/v1/payment/vnpay-return"


# PayPal Sandbox Configuration
paypal:
  client:
    id: "AVQPOG0KRfz22PxqO-PHW3Njc37_ilyUixlxSzuI_s2vQonptF76NS-sldORXjjDXlXgAezNtNywik0y"
    secret: "EN15GcZTDDaBwi-2V3mRgUja08KSlUPWa-xhf71LQg_gbM2ciwVu7e9jSbIgbCcMRg_3ct91nIiPnJ6W"
  mode: "sandbox"
  return-url: "http://localhost:8080/api/v1/payment/paypal-return"
  cancel-url: "http://localhost:8080/api/v1/payment/paypal-cancel"



