# Cấu hình chung
server:
  port: 8080  # Cổng của ứng dụng
# Cấu hình kết nối cơ sở dữ liệu
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shopapp_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # Cấu hình kích thước pool kết nối

# Cấu hình JPA (Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: update  # Tự động tạo bảng nếu chưa có
    show-sql: true  # Hiển thị câu lệnh SQL trong console

# Cấu hình bảo mật
  security:
    enable: false
    user:
      name: admin
      password: password
